services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend_network
  fastapi_backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    image: fastapi_backend:latest
    ports:
      - "9000:9000"
      - "5678:5678"
    volumes:
      - ./backend:/app
      - ./backend/media:/media
      - ./backend/media:/backend/media
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000", "--lifespan", "on"]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
    networks:
      - backend_network
    stop_signal: SIGTERM
    stop_grace_period: 10s
networks:
  backend_network:
    driver: bridge